podTemplate(containers: [
  containerTemplate(
    name: 'python',
    image: 'python:3.11',
    command: 'cat',
    ttyEnabled: true
  )
]) {
  node(POD_LABEL) {
    container('python') {
      stage('Checkout') {
        checkout scm
      }

      stage('Install') {
        dir('repo-root/python-app') {
          sh 'pip install -r requirements.txt'
        }
      }
    }
  }
}
