pipeline {
  agent {
    kubernetes {
      label 'kaniko-agent'
    }
  }
  environment {
    DOCKER_IMAGE = 'ghcr.io/akinanny/python_mysql_expose:latest'
  }
  stages {
    stage('Build') {
      steps {
        container('kaniko') {
          withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
            sh '''
            echo "{\"auths\":{\"ghcr.io\":{\"username\":\"$USER\",\"password\":\"$PASS\"}}}" > /kaniko/.docker/config.json
            /kaniko/executor \
              --context `pwd` \
              --dockerfile `pwd`/Dockerfile \
              --destination=$DOCKER_IMAGE \
              --skip-tls-verify
            '''
          }
        }
      }
    }
  }
}
